#!/usr/bin/env ruby
# frozen_string_literal: true

# Wires native/ShareExtension/ into the Capacitor-generated Xcode project.
#
# `ios/` is regenerated by `cap add ios` and is gitignored, so the extension
# target cannot simply live in git. This script rebuilds it from scratch each
# time, which keeps "check out, run one command, get a signable app" true.
#
# Idempotent: it tears down anything a previous run added before rebuilding, so
# running it twice is the same as running it once.
#
# Usage: ruby scripts/add-share-extension.rb
# Needs the `xcodeproj` gem, which CocoaPods already depends on.

require "xcodeproj"

REPO_ROOT = File.expand_path("..", __dir__)
PROJECT_PATH = File.join(REPO_ROOT, "ios", "App", "App.xcodeproj")
NATIVE_DIR = File.join(REPO_ROOT, "native", "ShareExtension")
SWIFT_SOURCE = File.join(NATIVE_DIR, "ShareViewController.swift")
INFO_PLIST = File.join(NATIVE_DIR, "Info.plist")
ENTITLEMENTS = File.join(NATIVE_DIR, "ShareExtension.entitlements")
XCCONFIG = File.join(NATIVE_DIR, "Config.xcconfig")

EXT_NAME = "ShareExtension"
APP_TARGET_NAME = "App"
APP_DISPLAY_NAME = "marcador"
# One floor for the whole app. Capacitor generates 13.0; the extension's
# async/await and UTType use needs far less than 26, but a single modern floor
# beats maintaining a split.
DEPLOYMENT_TARGET = "26.0"

def die(message)
  warn "add-share-extension: #{message}"
  exit 1
end

die "no Xcode project at #{PROJECT_PATH} — run `bun run cap:add` first" unless File.exist?(PROJECT_PATH)
die "missing #{SWIFT_SOURCE}" unless File.exist?(SWIFT_SOURCE)

project = Xcodeproj::Project.open(PROJECT_PATH)
app_target = project.targets.find { |t| t.name == APP_TARGET_NAME }
die "no `#{APP_TARGET_NAME}` target — is this a Capacitor iOS project?" unless app_target

# --- Tear down a previous run ------------------------------------------------
# Order matters: the embed phase and dependency both reference the target, so
# they have to go before the target itself.
app_target.build_phases
          .grep(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
          .select { |p| p.name == "Embed App Extensions" }
          .each(&:remove_from_project)

app_target.dependencies
          .select { |d| d.target&.name == EXT_NAME }
          .each(&:remove_from_project)

project.targets.select { |t| t.name == EXT_NAME }.each do |t|
  t.product_reference&.remove_from_project
  t.remove_from_project
end

project.main_group[EXT_NAME]&.remove_from_project

# --- Signing team ------------------------------------------------------------
# Xcode cannot sign either target without a team, and because ios/ is thrown
# away and rebuilt on every run, setting it by hand in the UI lasts exactly
# until the next one. MARCADOR_DEV_TEAM wins; otherwise the team is read off the
# one installed Apple Development certificate, which is unambiguous on a machine
# with a single developer account.
def development_team
  from_env = ENV["MARCADOR_DEV_TEAM"]
  return from_env unless from_env.nil? || from_env.empty?

  names = `security find-identity -v -p codesigning 2>/dev/null`
            .scan(/"(Apple Development: [^"]+)"/).flatten.uniq
  return nil unless names.length == 1

  # The team id is the certificate's organisational unit.
  subject = `security find-certificate -c "#{names.first}" -p 2>/dev/null | openssl x509 -noout -subject 2>/dev/null`
  subject[/OU\s*=\s*([A-Z0-9]+)/, 1]
end

TEAM = development_team

# --- Create the target -------------------------------------------------------
ext_target = project.new_target(:app_extension, EXT_NAME, :ios, DEPLOYMENT_TARGET)

app_settings = app_target.build_configurations.first.build_settings
# Apple requires the extension's bundle id to be a child of the app's, so derive
# it rather than hard-coding and letting the two drift.
app_bundle_id = app_settings["PRODUCT_BUNDLE_IDENTIFIER"] || "es.ricojam.marcador"

ext_target.build_configurations.each do |config|
  config.build_settings.merge!(
    # Without PRODUCT_NAME the wrapper is built as a bare ".appex" and two build
    # commands collide on that path.
    "PRODUCT_NAME" => "$(TARGET_NAME)",
    "PRODUCT_BUNDLE_IDENTIFIER" => "#{app_bundle_id}.#{EXT_NAME}",
    # An extension whose version differs from its host app fails archive
    # validation, so mirror the app's.
    "CURRENT_PROJECT_VERSION" => app_settings["CURRENT_PROJECT_VERSION"] || "1",
    "MARKETING_VERSION" => app_settings["MARKETING_VERSION"] || "1.0",
    # Paths are relative to SRCROOT (ios/App); native/ is two levels up.
    "INFOPLIST_FILE" => "../../native/ShareExtension/Info.plist",
    "GENERATE_INFOPLIST_FILE" => "NO",
    "IPHONEOS_DEPLOYMENT_TARGET" => DEPLOYMENT_TARGET,
    "SWIFT_VERSION" => "5.0",
    "TARGETED_DEVICE_FAMILY" => "1,2",
    "SKIP_INSTALL" => "YES",
    "CODE_SIGN_STYLE" => "Automatic",
    "DEVELOPMENT_TEAM" => TEAM,
    "LD_RUNPATH_SEARCH_PATHS" =>
      "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks",
    # Catalyst is what puts marcador in the macOS share menu.
    "SUPPORTS_MACCATALYST" => "YES",
    # Scoped to the macOS SDK: macOS sandboxes every extension and denies the
    # POST without it, while an iOS provisioning profile carries no such
    # entitlement and would fail to sign if we applied it everywhere.
    "CODE_SIGN_ENTITLEMENTS[sdk=macosx*]" =>
      "../../native/ShareExtension/ShareExtension.entitlements",
  )
end

# --- Source files ------------------------------------------------------------
# Referenced in place: native/ stays the source of truth, ios/ stays disposable.
group = project.main_group.new_group(EXT_NAME, NATIVE_DIR)
ext_target.add_file_references([group.new_file(SWIFT_SOURCE)])
group.new_file(INFO_PLIST)
group.new_file(ENTITLEMENTS) if File.exist?(ENTITLEMENTS)

# --- Server address and token ------------------------------------------------
# Config.xcconfig supplies MARCADOR_SERVER_URL and MARCADOR_SHARE_TOKEN, which
# Info.plist substitutes at build time. It is gitignored, so it may be missing on
# a fresh checkout; wire it either way and warn, because a build that produces an
# unconfigured extension is more useful for debugging than no build at all.
config_ref = group.new_file(XCCONFIG)
ext_target.build_configurations.each do |config|
  config.base_configuration_reference = config_ref
end

unless File.exist?(XCCONFIG)
  warn "add-share-extension: note — #{XCCONFIG} is missing, so the extension " \
       "will build with an empty server URL and token. Copy Config.xcconfig.example."
end

# --- Embed it in the app -----------------------------------------------------
app_target.add_dependency(ext_target)
embed_phase = app_target.new_copy_files_build_phase("Embed App Extensions")
embed_phase.symbol_dst_subfolder_spec = :plug_ins
embed_phase.add_file_reference(ext_target.product_reference).settings =
  { "ATTRIBUTES" => ["RemoveHeadersOnCopy"] }

# --- Catalyst + a matching floor on the host app -----------------------------
# The share row only appears on macOS if BOTH the app and the extension build
# for Catalyst. Capacitor generates the app iOS-only, so flip it here rather
# than making it a hand-click that the next `cap add` silently wipes.
app_target.build_configurations.each do |config|
  config.build_settings["SUPPORTS_MACCATALYST"] = "YES"
  config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = DEPLOYMENT_TARGET
  config.build_settings["CODE_SIGN_STYLE"] = "Automatic"
  config.build_settings["DEVELOPMENT_TEAM"] = TEAM if TEAM
end

project.build_configurations.each do |config|
  config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = DEPLOYMENT_TARGET
end

project.save

# --- App name ----------------------------------------------------------------
# Capacitor derives both name keys from PRODUCT_NAME, which is "App". The Dock
# and app switcher read CFBundleDisplayName; the macOS Sharing settings pane
# reads CFBundleName. Set both or the app shows up somewhere as a bare "App".
app_info_plist = File.join(REPO_ROOT, "ios", "App", "App", "Info.plist")
if File.exist?(app_info_plist)
  plist = Xcodeproj::Plist.read_from_path(app_info_plist)
  plist["CFBundleName"] = APP_DISPLAY_NAME
  plist["CFBundleDisplayName"] = APP_DISPLAY_NAME
  Xcodeproj::Plist.write_to_path(plist, app_info_plist)
end

if TEAM
  puts "add-share-extension: signing with team #{TEAM}"
else
  puts "add-share-extension: no signing team found — set one on both targets in"
  puts "                     Xcode, or export MARCADOR_DEV_TEAM before running."
end

puts "add-share-extension: wired #{EXT_NAME} (#{app_bundle_id}.#{EXT_NAME}) into #{APP_TARGET_NAME}"
